apiVersion: v1
kind: Namespace
metadata:
  name: uat
  labels:
    name: uat
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: uat
spec:
  hard:
    pods: "4"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-quota-deployment
  namespace: uat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resource-quota-deployment
  template:
    metadata:
      labels:
        app: resource-quota-deployment
    spec:
      containers:
        - name: resource-quota-pod
          image: nginx:latest
          resources:
            requests:
              memory: 500Mi
              cpu: 500m
            limits:
              memory: 1Gi
              cpu: 1
