apiVersion: v1
kind: Pod
metadata:
  name: liveness
  labels:
    app: liveness
spec:
  containers:
    - name: liveness
      image: busybox
      command:
        [
          "sh",
          "-c",
          "touch /tmp/healthy && sleep 30 && rm -rf /tmp/healthy && sleep 600",
        ]
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5 # Delay before the first probe
        periodSeconds: 5 # How often to probe
        # successThreshold: 1 # Number of successful probes before considering the container healthy
        # failureThreshold: 3 # Number of failed probes before considering the container unhealthy
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 100m
          memory: 100Mi
