apiVersion: v1
kind: Pod
metadata:
  name: goproxy
  labels:
    app: goproxy
spec:
  containers:
    - name: goproxy
      image: goproxy
      command:
        [
          "sh",
          "-c",
          "touch /tmp/healthy && sleep 30 && rm -rf /tmp/healthy && sleep 600",
        ]
      ports:
        - containerPort: 8080
      livenessProbe: # The probe to use for liveness
        tcpSocket: # The type of probe to use
          port: 8080 # The port number to probe
        initialDelaySeconds: 5 # Delay before the first probe
        periodSeconds: 5 # How often to probe
        # successThreshold: 1 # Number of successful probes before considering the container healthy
        # failureThreshold: 3 # Number of failed probes before considering the container unhealthy
      readinessProbe: # The probe to use for readiness
        tcpSocket: # The type of probe to use
          port: 8080 # The port number to probe
        initialDelaySeconds: 5 # Delay before the first probe
        periodSeconds: 5 # How often to probe
        # successThreshold: 1 # Number of successful probes before considering the container healthy
        # failureThreshold: 3 # Number of failed probes before considering the container unhealthy
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 100m
          memory: 100Mi
