apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-cpu-limit-range
  namespace: dev
spec:
  limits:
    - default: # this section defines default limits
        cpu: 1 # 1 core
        memory: 512Mi # 512MB
      defaultRequest: # this section defines default requests
        cpu: 500m # 500m core
        memory: 256Mi # 256MB
      type: Container
