apiVersion: v1
kind: Pod
metadata:
  name: podtest1
  labels:
    app: frontend
    env: dev
spec:
  containers:
    - name: cont1
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest2
  labels:
    app: backend
    env: dev
spec:
  containers:
    - name: cont2
      image: nginx:alpine
